#sales_router/src/sales_clusterization/Dockerfile.clusterization

FROM psilas85/sales_router-base:latest

WORKDIR /app

COPY ./src/sales_clusterization ./src/sales_clusterization
COPY ./src/database ./src/database
COPY ./requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8004

CMD ["uvicorn", "sales_clusterization.api.cluster_api:app", "--host", "0.0.0.0", "--port", "8004"]

