#sales_router/src/geocoding_engine/Dockerfile.geocoding

FROM psilas85/sales_router-base:latest

WORKDIR /app

ENV PYTHONPATH=/app/src

# ----------------------------------------------------
# instala dependências da raiz do projeto
# ----------------------------------------------------

COPY ./requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -r /tmp/requirements.txt

# ----------------------------------------------------
# copia código
# ----------------------------------------------------

COPY ./src/geocoding_engine /app/src/geocoding_engine
COPY ./src/database /app/src/database

EXPOSE 8007

CMD ["uvicorn","src.geocoding_engine.api.main:app","--host","0.0.0.0","--port","8007"]